export enum FrsEdgeType {
	Calibration = 'Calibration',
	SN = 'S-N',
	SpaSpp = 'Spa-Spp',
	NA = 'N-A',
	SppA = 'Spp-A',
	NB = 'N-B',
	NMe = 'N-Me',
	NPog = 'N-Pog',
	ArGo = 'Ar-Go',
	MeGo = 'Me-Go',
	GoaPog2 = 'Goa-Pog\'',
	InOK1ApOK1 = 'InOK1-ApOK1',
	InUK1ApUK1 = 'InUK1-ApUK1',
	VPOcPHPOcP = 'vPocP-hPOcP',
	ProNPog2 = 'ProN-Pog\'',
}
