export enum FrsMarkType {
	S = 'S',
	N = 'N',
	Spa = 'Spa',
	Spp = 'Spp',
	Sp = 'Sp',
	A = 'A',
	Ar = 'Ar',
	Me = 'Me',
	Pog = 'Pog',
	B = 'B',
	Tgp = 'Tgp',
	Tga = 'Tga',
	Go = 'Go',
	Goa = 'Goa',
	InOK1 = 'InOK1',
	ApOK1 = 'ApOK1',
	InUK1 = 'InUK1',
	ApUK1 = 'ApUK1',
	VPOcP = 'vPOcP',
	HPOcP = 'hPOcP',
	Ls = 'Ls',
	Li = 'Li',
	ProN = 'ProN',
	Pog2 = "Pog'",
	Calibration1 = 'Calibration1',
	Calibration2 = 'Calibration2',
}
