import { marker as _ } from '@biesbjerg/ngx-translate-extract-marker'
import {
	FrsAngleCalculation,
	FrsAngleMultiplicationCalculation,
	FrsAngleSumCalculation,
	FrsCalculationConfigDto,
	FrsCalculationDataType,
	FrsCalculationType,
	FrsCalculationUnit,
	FrsDistanceCalculation,
	FrsEdgeType,
	FrsInterpretation,
	FrsIntersectionDistanceCalculation,
	FrsMarkType,
	FrsQuotientCalculation,
} from '@dentalyzer/analysis/frs'
import { Gender } from '@dentalyzer/models'

export const frsCalculationsConfig: FrsCalculationConfigDto[] = [
	{
		id: FrsCalculationType.SNA,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleCalculation>{
			id: FrsCalculationDataType.Angle,
			edge1: FrsEdgeType.SN,
			edge2: FrsEdgeType.NA,
			isLeft: false,
		},
		targetValue: 81,
		deviation: 3,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.SNA} + '.Same' `),
			greater: _(`${FrsCalculationType.SNA} + '.Greater'`),
			smaller: _(`${FrsCalculationType.SNA} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.SNB,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleCalculation>{
			id: FrsCalculationDataType.Angle,
			edge1: FrsEdgeType.SN,
			edge2: FrsEdgeType.NB,
			isLeft: false,
		},
		targetValue: 79,
		deviation: 3,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.SNB} + '.Same' `),
			greater: _(`${FrsCalculationType.SNB} + '.Greater'`),
			smaller: _(`${FrsCalculationType.SNB} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.SNPog,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleCalculation>{
			id: FrsCalculationDataType.Angle,
			edge1: FrsEdgeType.SN,
			edge2: FrsEdgeType.NPog,
			isLeft: false,
		},
		targetValue: 80,
		deviation: 3,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.SNPog} + '.Same' `),
			greater: _(`${FrsCalculationType.SNPog} + '.Greater'`),
			smaller: _(`${FrsCalculationType.SNPog} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.ANB,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleCalculation>{
			id: FrsCalculationDataType.Angle,
			edge1: FrsEdgeType.NA,
			edge2: FrsEdgeType.NB,
			isLeft: true,
		},
		targetValue: 2,
		deviation: 2,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.ANB} + '.Same' `),
			greater: _(`${FrsCalculationType.ANB} + '.Greater'`),
			smaller: _(`${FrsCalculationType.ANB} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.ANBIndiv,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleMultiplicationCalculation>{
			id: FrsCalculationDataType.AngleMultiplication,
			targetStartValue: -35.16,
			targetFactor1: 0.4,
			targetAngle1: FrsCalculationType.SNA,
			targetFactor2: 0.2,
			targetAngle2: FrsCalculationType.SNMeGo,
			valueDuplicate: FrsCalculationType.ANB,
		},
		targetValue: undefined,
		deviation: undefined,
		interpretation: undefined,
	},
	{
		id: FrsCalculationType.Wits,
		unit: FrsCalculationUnit.Millimeter,
		data: <FrsIntersectionDistanceCalculation>{
			id: FrsCalculationDataType.IntersectionDistance,
			edge: FrsEdgeType.VPOcPHPOcP,
			point1: FrsMarkType.A,
			point2: FrsMarkType.B,
		},
		targetValue: new Map([
			[Gender.Male, -1],
			[Gender.FEMALE, 0],
		]),
		deviation: 2,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.Wits} + '.Same' `),
			greater: _(`${FrsCalculationType.Wits} + '.Greater'`),
			smaller: _(`${FrsCalculationType.Wits} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.SNMeGo,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleSumCalculation>{
			id: FrsCalculationDataType.AngleSum,
			angle1: FrsCalculationType.SNSpP,
			angle2: FrsCalculationType.SpPMeGo,
		},
		targetValue: 32,
		deviation: 5,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.SNMeGo} + '.Same' `),
			greater: _(`${FrsCalculationType.SNMeGo} + '.Greater'`),
			smaller: _(`${FrsCalculationType.SNMeGo} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.SNSpP,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleCalculation>{
			id: FrsCalculationDataType.Angle,
			edge1: FrsEdgeType.SN,
			edge2: FrsEdgeType.SpaSpp,
			isLeft: true,
		},
		targetValue: 7,
		deviation: 3,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.SNSpP} + '.Same' `),
			greater: _(`${FrsCalculationType.SNSpP} + '.Greater'`),
			smaller: _(`${FrsCalculationType.SNSpP} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.SpPMeGo,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleCalculation>{
			id: FrsCalculationDataType.Angle,
			edge1: FrsEdgeType.SpaSpp,
			edge2: FrsEdgeType.MeGo,
			isLeft: true,
		},
		targetValue: 25,
		deviation: 5,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.SpPMeGo} + '.Same' `),
			greater: _(`${FrsCalculationType.SpPMeGo} + '.Greater'`),
			smaller: _(`${FrsCalculationType.SpPMeGo} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.SGONMe,
		unit: FrsCalculationUnit.Percent,
		data: <FrsQuotientCalculation>{
			id: FrsCalculationDataType.Quotient,
			line1point1: FrsMarkType.S,
			line1point2: FrsMarkType.Go,
			line2point1: FrsMarkType.N,
			line2point2: FrsMarkType.Me,
		},
		targetValue: 65,
		deviation: 4,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.SGONMe} + '.Same' `),
			greater: _(`${FrsCalculationType.SGONMe} + '.Greater'`),
			smaller: _(`${FrsCalculationType.SGONMe} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.ArGoMe,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleCalculation>{
			id: FrsCalculationDataType.Angle,
			edge1: FrsEdgeType.ArGo,
			edge2: FrsEdgeType.MeGo,
			isLeft: false,
		},
		targetValue: 126,
		deviation: 6,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.ArGoMe} + '.Same' `),
			greater: _(`${FrsCalculationType.ArGoMe} + '.Greater'`),
			smaller: _(`${FrsCalculationType.ArGoMe} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.NSpSpMe,
		unit: FrsCalculationUnit.Percent,
		data: <FrsQuotientCalculation>{
			id: FrsCalculationDataType.Quotient,
			line1point1: FrsMarkType.N,
			line1point2: FrsMarkType.Sp,
			line2point1: FrsMarkType.Sp,
			line2point2: FrsMarkType.Me,
		},
		targetValue: 80,
		deviation: 6,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.NSpSpMe} + '.Same' `),
			greater: _(`${FrsCalculationType.NSpSpMe} + '.Greater'`),
			smaller: _(`${FrsCalculationType.NSpSpMe} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.OK1SN,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleCalculation>{
			id: FrsCalculationDataType.Angle,
			edge1: FrsEdgeType.InOK1ApOK1,
			edge2: FrsEdgeType.SN,
			isLeft: true,
		},
		targetValue: 102,
		deviation: 5,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.OK1SN} + '.Same' `),
			greater: _(`${FrsCalculationType.OK1SN} + '.Greater'`),
			smaller: _(`${FrsCalculationType.OK1SN} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.OK1SpP,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleCalculation>{
			id: FrsCalculationDataType.Angle,
			edge1: FrsEdgeType.InOK1ApOK1,
			edge2: FrsEdgeType.SpaSpp,
			isLeft: false,
		},
		targetValue: 70,
		deviation: 5,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.OK1SpP} + '.Same' `),
			greater: _(`${FrsCalculationType.OK1SpP} + '.Greater'`),
			smaller: _(`${FrsCalculationType.OK1SpP} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.UK1MeGo,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleCalculation>{
			id: FrsCalculationDataType.Angle,
			edge1: FrsEdgeType.InUK1ApUK1,
			edge2: FrsEdgeType.MeGo,
			isLeft: false,
		},
		targetValue: 93,
		deviation: 6,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.UK1MeGo} + '.Same' `),
			greater: _(`${FrsCalculationType.UK1MeGo} + '.Greater'`),
			smaller: _(`${FrsCalculationType.UK1MeGo} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.OK1UK1,
		unit: FrsCalculationUnit.Degree,
		data: <FrsAngleCalculation>{
			id: FrsCalculationDataType.Angle,
			edge1: FrsEdgeType.InOK1ApOK1,
			edge2: FrsEdgeType.InUK1ApUK1,
			isLeft: true,
		},
		targetValue: 131,
		deviation: 9,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.OK1UK1} + '.Same' `),
			greater: _(`${FrsCalculationType.OK1UK1} + '.Greater'`),
			smaller: _(`${FrsCalculationType.OK1UK1} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.OK1NA,
		unit: FrsCalculationUnit.Millimeter,
		data: <FrsDistanceCalculation>{
			id: FrsCalculationDataType.Distance,
			edge: FrsEdgeType.NA,
			point: FrsMarkType.InOK1,
		},
		targetValue: 4,
		deviation: 2,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.OK1NA} + '.Same' `),
			greater: _(`${FrsCalculationType.OK1NA} + '.Greater'`),
			smaller: _(`${FrsCalculationType.OK1NA} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.UK1NB,
		unit: FrsCalculationUnit.Millimeter,
		data: <FrsDistanceCalculation>{
			id: FrsCalculationDataType.Distance,
			edge: FrsEdgeType.NB,
			point: FrsMarkType.InUK1,
		},
		targetValue: 4,
		deviation: 2,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.UK1NB} + '.Same' `),
			greater: _(`${FrsCalculationType.UK1NB} + '.Greater'`),
			smaller: _(`${FrsCalculationType.UK1NB} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.SppASN,
		unit: FrsCalculationUnit.Percent,
		data: <FrsQuotientCalculation>{
			id: FrsCalculationDataType.Quotient,
			line1point1: FrsMarkType.Spp,
			line1point2: FrsMarkType.A,
			line2point1: FrsMarkType.S,
			line2point2: FrsMarkType.N,
		},
		targetValue: 68,
		deviation: 4,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.SppASN} + '.Same' `),
			greater: _(`${FrsCalculationType.SppASN} + '.Greater'`),
			smaller: _(`${FrsCalculationType.SppASN} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.GoaPogSN,
		unit: FrsCalculationUnit.Percent,
		data: <FrsQuotientCalculation>{
			id: FrsCalculationDataType.Quotient,
			line1point1: FrsMarkType.Goa,
			line1point2: FrsMarkType.Pog,
			line2point1: FrsMarkType.S,
			line2point2: FrsMarkType.N,
		},
		targetValue: 105,
		deviation: 5,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.GoaPogSN} + '.Same' `),
			greater: _(`${FrsCalculationType.GoaPogSN} + '.Greater'`),
			smaller: _(`${FrsCalculationType.GoaPogSN} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.SppAGoaPog,
		unit: FrsCalculationUnit.Percent,
		data: <FrsQuotientCalculation>{
			id: FrsCalculationDataType.Quotient,
			line1point1: FrsMarkType.Spp,
			line1point2: FrsMarkType.A,
			line2point1: FrsMarkType.Goa,
			line2point2: FrsMarkType.Pog,
		},
		targetValue: 64,
		deviation: 4,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.SppAGoaPog} + '.Same' `),
			greater: _(`${FrsCalculationType.SppAGoaPog} + '.Greater'`),
			smaller: _(`${FrsCalculationType.SppAGoaPog} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.LsEsthetic,
		unit: FrsCalculationUnit.Millimeter,
		data: <FrsDistanceCalculation>{
			id: FrsCalculationDataType.Distance,
			edge: FrsEdgeType.ProNPog2,
			point: FrsMarkType.Ls,
		},
		targetValue: -4,
		deviation: 2,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.LsEsthetic} + '.Same' `),
			greater: _(`${FrsCalculationType.LsEsthetic} + '.Greater'`),
			smaller: _(`${FrsCalculationType.LsEsthetic} + '.Smaller'`),
		},
	},
	{
		id: FrsCalculationType.LiEsthetic,
		unit: FrsCalculationUnit.Millimeter,
		data: <FrsDistanceCalculation>{
			id: FrsCalculationDataType.Distance,
			edge: FrsEdgeType.ProNPog2,
			point: FrsMarkType.Li,
		},
		targetValue: -2,
		deviation: 2,
		interpretation: <FrsInterpretation>{
			same: _(`${FrsCalculationType.LiEsthetic} + '.Same' `),
			greater: _(`${FrsCalculationType.LiEsthetic} + '.Greater'`),
			smaller: _(`${FrsCalculationType.LiEsthetic} + '.Smaller'`),
		},
	},
]
